### ISSUE TITLE
Define what external dependencies are required

### ISSUE THREAD

**Issue by shackra** [ubolonton/emacs-tree-sitter#10]
After installing Rust (with Rustup) and running './bin/build` I get this:

```
❯ ./bin/build
   Compiling emacs_module v0.10.0
error: failed to run custom build command for `emacs_module v0.10.0`

Caused by:
  process didn't exit successfully: `/home/jorge/code/emacs/emacs-tree-sitter/target/debug/build/emacs_module-a6842dec63007bb2/build-script-build` (exit code: 101)
--- stderr
./include/emacs-module.h:24:10: fatal error: 'stddef.h' file not found
./include/emacs-module.h:24:10: fatal error: 'stddef.h' file not found, err: true
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

It seems I don't have all dependencies on my Linux Mint 19.x (work laptop; I use Arch Linux at home and I'm more familiar with it), knowing what extra packages to install would be of use. I got Emacs from Snap

I have `build-essential` installed.

**Comment by yyoncho** [comment]
I think that you need linux-headers-4.15.0-20 for that(and I think that there were 2-3 more packages).

**Comment by shackra** [comment]
I already have that package installed, so, maybe the solution are those three mysterious packages

**Comment by yyoncho** [comment]
Might be of help:

```
➜  ~ dpkg -S stddef.h                                                    
linux-headers-4.15.0-20: /usr/src/linux-headers-4.15.0-20/include/uapi/linux/stddef.h
libclang-common-6.0-dev: /usr/lib/llvm-6.0/lib/clang/6.0.0/include/stddef.h
linux-libc-dev:amd64: /usr/include/linux/stddef.h
libclang-common-8-dev: /usr/lib/llvm-8/lib/clang/8.0.1/include/stddef.h
libgcc-7-dev:amd64: /usr/lib/gcc/x86_64-linux-gnu/7/include/stddef.h
libgcc-8-dev:amd64: /usr/lib/gcc/x86_64-linux-gnu/8/include/stddef.h
linux-headers-4.15.0-20: /usr/src/linux-headers-4.15.0-20/include/linux/stddef.h
```

**Comment by shackra** [comment]
it is weird because I also installed libgcc-8-dev but the rust toolchain is unable to reach this file

**Comment by shackra** [comment]
The following is the list of packages installed on my system's work laptop: 
[packages-installed.txt](https://github.com/ubolonton/emacs-tree-sitter/files/3692551/packages-installed.txt)

and, as shown below I have most of the packages pointed out by @yyoncho installed:

```
cat /tmp/packages-installed.txt | grep "linux-headers-4.15.0-20\|libclang-common-6.0-dev\|linux-libc-dev\|libclang-common-8-dev\|libgcc-7-dev\|libgcc-8-dev\|linux-headers-4.15.0-20"
libclang-common-8-dev  1:8-3~ubuntu18.04.1     Clang library - Common development package
libgcc-7-dev    7.4.0-1ubuntu1~18.04.1  GCC support library (development files)
libgcc-8-dev    8.3.0-6ubuntu1~18.04.1  GCC support library (development files)
linux-headers-4.15.0-20 4.15.0-20.21    Header files related to Linux kernel version 4.15.0
linux-headers-4.15.0-20-generic 4.15.0-20.21    Linux kernel headers for version 4.15.0 on 64 bit x86 SMP
linux-libc-dev  4.15.0-64.73    Linux Kernel Headers for development
```

**Comment by ubolonton** [comment]
I only tested this on Ubuntu. It may be the case that the Ubuntu installations I use (CI and my own server) already have the necessary packages, with correct configuration.

`emacs-module-rs` uses `bindgen` to generate the raw bindings. It uses `clang` to search for system header files, not `gcc`. You have `libclang-common-8-dev` installed, so it may be an issue with include path configuration, not missing packages.

Can you check what these commands print?

```bash
sudo find / -name stddef.h

echo $CPATH

echo $C_INCLUDE_PATH

clang -E -x c - -v < /dev/null
```

**Comment by ubolonton** [comment]
On a related note, once #2 is done, there will be pre-built binaries, so people don't have to deal with this kind of headache.

**Comment by shackra** [comment]
@ubolonton it turns out I did not had `clang` installed to begin with. I installed it and was able to build
