### ISSUE TITLE
Distribution of "language objects" for a major mode

### ISSUE THREAD

**Issue by sogaiu** [ubolonton/emacs-tree-sitter#101]
I've made some progress on a new Janet major mode that uses emacs-tree-sitter (as discussed here: https://github.com/ubolonton/emacs-tree-sitter/issues/95#issuecomment-760585198)

It now has some support for:

* indentation
* highlighting
* folding (comment blocks and docstrings)
* imenu

In each case emacs-tree-sitter is used.

I'd like to make it generally available, but regarding the platform-specific grammar bits as [noted in the EmacsConf 2020 presentation](https://youtu.be/ZwibVdNtFjs?t=1344):

> The plan is that eventually these files should be provided by the language major modes themselves.  But in order to do that we need better tooling.

Is it still recommended then to make a PR to have the relevant grammar be part of `tree-sitter-langs`?

**Comment by ubolonton** [comment]
There hasn't been tooling improvement for this, so it's still easier to let `tree-sitter-langs` distribute the grammar, unless the new major mode already have its own binary distribution mechanisms in place.

**Comment by sogaiu** [comment]
Thank you!

**Comment by sogaiu** [comment]
I am confused about the name of the shared library.

When I build it within emacs-tree-sitter's project directory using `make ensure/janet-simple` the resulting file is located in `langs/bin` and named `janet-simple.so`, using a hyphen.

When I build the shared library within the tree-sitter-janet-simple project, I end up with a file named `janet_simple.so`, which uses an underscore.

I tested with `tree-sitter-c-sharp` with similar results (i.e. one way yields `c-sharp.so` and the other way yields `c_sharp.so`).

Is this something I need to be concerned with?

**Comment by ubolonton** [comment]
The CLI tool `tree-sitter` outputs names with underscores: `janet_simple.so`.
The function `tree-sitter-langs-compile` converts underscores to hyphens, to make the names more Emacs-y: `janet-simple.so`.
The function `tree-sitter-load` looks for both (hyphens first): `janet-simple.so` then `janet_simple.so`.
Further Emacs tools should assume hyphens. 

This was introduced in [0.12.2](https://github.com/ubolonton/emacs-tree-sitter/blob/master/CHANGELOG.md#0122---2020-12-15).

It shouldn't be a concern.

**Comment by sogaiu** [comment]
Thank you for the explanation.
