### ISSUE TITLE
Why are highlighting queries different from upstream's?

### ISSUE THREAD

**Issue by jcs090218** [ubolonton/emacs-tree-sitter#108]
https://github.com/ubolonton/emacs-tree-sitter/blob/67155b30f92fb1f0c9316db1ec52a12dc4b95810/langs/queries/css/highlights.scm#L37

Why the above line is different from the source? 

See [tree-sitter/tree-sitter-css/queries/highlights.scm#L32](https://github.com/tree-sitter/tree-sitter-css/blob/23f2cb97d47860c517f67f03e1f4b621d5bd2085/queries/highlights.scm#L32)

**Comment by ubolonton** [comment]
From the related issue #42:

> Most of the queries in official language repositories are pretty bare-bone, and may not fit well with existing Emacs's conventions. It's my intention for `tree-sitter-langs` to maintain its own version of the highlighting queries. (Later on, that will be job of major modes that use tree-sitter).

**Comment by jcs090218** [comment]
Thanks for the explanation!
