### ISSUE TITLE
Installing tree-sitter breaks evil motion rebinds

### ISSUE THREAD

**Issue by NightH4nter** [ubolonton/emacs-tree-sitter#123]
Hi. I have [this](https://gist.github.com/NightH4nter/c47b705eca09f1f78745d02cb4c7ecf0) in my init.el. Without
```elisp
(straight-use-package 'tree-sitter)
(straight-use-package 'tree-sitter-langs)
(require 'tree-sitter)
(require 'tree-sitter-langs)
(add-hook 'rust-mode-hook #'tree-sitter-mode)
```
`jkl;` in `dired` and `help` buffers work as they're expected to with the corresponding remappings. But once I uncomment these lines (like in `init.el` above), the keybindings revert back to `hjkl`.

Output of `C-h, k, k` pressed in `dired` buffer with those lines commented out:
![image](https://user-images.githubusercontent.com/31319604/111270549-e9d79b80-8627-11eb-8d4a-c844a3c3378d.png)

Same, but with those lines uncommented:
![image](https://user-images.githubusercontent.com/31319604/111270695-14295900-8628-11eb-8f82-ce9cee000ff5.png)

I'm very new to Emacs and probably don't understand something, but I'd appreciate some help on it. Thanks.

**Comment by ubolonton** [comment]
This looks like an bug with key definition order in `evil`/`general`.

You'd get the same issue by replacing the `tree-sitter` init code with  `(require 'dired)`. Putting that after the key redefinitions works.

> I'm very new to Emacs and probably don't understand something, but I'd appreciate some help on it. Thanks.

You can try debugging `evil`/`general` key definition order by logging calls to `define-key`. For example, add this to the top of your `init.el`:

```emacs-lisp
(define-advice define-key (:before (_keymap key def &rest _) who-defines-k)
  (when (equal key "k")
    (message "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    (message "k is getting redefined into %s" def)
    ;; Print the backtrace.
    (mapbacktrace (lambda (_evald func args _flags)
                    ;; The bug seems to depend on lib load order, so log more for loads.
                    (if (memq func '(load require))
                        (message "  --  %s  :  %s" func args)
                      (message "  --  %s" func))))))
```

**Comment by NightH4nter** [comment]
> This looks like an bug with key definition order in evil/general.

Actually it's been working the same way back when I was not using general.el. 

> You'd get the same issue by replacing the tree-sitter init code with (require 'dired). Putting that after the key redefinitions works.

Yeah, this:

```emacs-lisp
(general-define-key
 :states '(motion, normal, visual, operator)
 "j" 'evil-backward-char
 "k" 'evil-next-line
 "l" 'evil-previous-line
 ";" 'evil-forward-char
 )

(require 'tree-sitter)
(require 'tree-sitter-langs)
(add-hook 'rust-mode-hook #'tree-sitter-mode)
(global-tree-sitter-mode)
(add-hook 'tree-sitter-after-on-hook #'tree-sitter-hl-mode)
;(require 'tree-sitter-hl)
```
actually worked fine. At least, for `dired` and and `help`.
