### ISSUE TITLE
file-missing "Cannot open load file" "file or directory not found" "tree-sitter-dyn"

### ISSUE THREAD

**Issue by shackra** [ubolonton/emacs-tree-sitter#13]
after successfully building the bindings and adding the repository to my `load-path` and evaluating `(require 'tree-sitter)` I get the following error:

```
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No existe el archivo o el directorio" "tree-sitter-dyn")
  require(tree-sitter-dyn)
  eval-buffer(#<buffer  *load*-454245> nil "/home/jorge/code/emacs/emacs-tree-sitter/tree-sitter-core.el" nil t)  ; Reading at buffer position 306
  load-with-code-conversion("/home/jorge/code/emacs/emacs-tree-sitter/tree-sitter-core.el" "/home/jorge/code/emacs/emacs-tree-sitter/tree-sitter-core.el" nil t)
  require(tree-sitter-core)
  eval-buffer(#<buffer  *load*> nil "/home/jorge/code/emacs/emacs-tree-sitter/tree-sitt..." nil t)  ; Reading at buffer position 778
  load-with-code-conversion("/home/jorge/code/emacs/emacs-tree-sitter/tree-sitter.el" "/home/jorge/code/emacs/emacs-tree-sitter/tree-sitter.el" nil t)
  require(tree-sitter)
  (progn (require 'tree-sitter))
  eval((progn (require 'tree-sitter)) t)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

This is the content of the root of the project, locally:

```
❯ tree -a -L 1
.
├── .azure-pipelines
├── bin
├── Cargo.lock
├── Cargo.toml
├── Cask
├── .git
├── .gitignore
├── grammars
├── README.md
├── src
├── target
├── .travis.yml
├── tree-sitter-core.el
├── tree-sitter-debug.el
├── tree-sitter-dyn.so
├── tree-sitter.el
└── tree-sitter-tests.el

6 directories, 11 files
```

**Comment by shackra** [comment]
- Linux Mint 19.2 Tessa
- it evals to `nil` and the variable is not defined
- module-load is a void function

**Comment by shackra** [comment]
With the latest two items:

- now it evals to `t` and the suffix is `.so`
- the evaluation of that returns `t` too.

the repository directory is part of the load-path variable, so, at this point I don't know what's wrong

**Comment by ubolonton** [comment]
Sorry I forgot about this. Have you tried using `module-load` directly, after recompiling Emacs with dynamic module support?

**Comment by shackra** [comment]
If I understand you correctly, yes, I tried that and worked that way, so is not my dynamic module support.

**Comment by ubolonton** [comment]
I mean, have you tried `(module-load "full/path/to/tree-sitter-dyn.so")` after recompiling Emacs?

`require` uses `module-load` underneath, and was/is buggy in certain combinations of Emacs+OS.

`Cannot open load file` looks like an error reported by `require`.

Using `module-load` directly would have reported `Module could not be opened`.

**Comment by shackra** [comment]
also, running `(require 'tree-sitter-dyn)` works, too (after evaluating `(add-to-list 'load-path "/home/jorge/code/emacs/emacs-tree-sitter")`).

**Comment by ubolonton** [comment]
So it's now working in your setup, or am I misunderstanding?

**Comment by shackra** [comment]
it works, but if I run `make test` the command files, this has to be something related to my Emacs setup maybe? there is a chance that running `make test` loads my configuration and because I don't have `(add-to-list 'load-path "/home/jorge/code/emacs/emacs-tree-sitter")` anywhere in it may be the cause of the failure

So, if I'm right (I will check the code related to the testing right now) this should work differently I think

**Comment by shackra** [comment]
Okay, I think I know what's going on.

in `bin/env.bash` you have an export for EMACS with the name of the `emacs` command, if I do `which emacs` this name points to `/usr/bin/emacs` but this is wrong because I use [Emacs from Snapcraft](https://snapcraft.io/emacs), the Emacs provided by Snapcraft is the one with the dynamic module turned on.

Gonna test something and provide a pull request if my experiment works

**Comment by shackra** [comment]
PR made, please review it
