### ISSUE TITLE
How to create an evil text object for bash functions using emacs-tree-sitter?

### ISSUE THREAD

**Issue by NightMachinary** [ubolonton/emacs-tree-sitter#147]
How to create an evil text object for bash functions using emacs-tree-sitter?

**Comment by theHamsta** [comment]
I have no idea on how to do that in emacs. But it would be great to team up and share queries as we have already a bunch of texting extra defined here for Neovim https://github.com/nvim-treesitter/nvim-treesitter-textobjects

**Comment by ubolonton** [comment]
This depends on the mechanism to define new text objects in `evil`. `tree-sitter` helps with locating the objects.

For a simple text object like a function, `tree-sitter-node-at-point` could be enough.

A more generic implementation could define interfaces to plug in language-specific text-object queries, like what @theHamsta mentioned above.
