### ISSUE TITLE
Emacs mailing list. 

### ISSUE THREAD

**Issue by Ergus** [ubolonton/emacs-tree-sitter#151]
Hi:

 Recently it has been commented in the emacs devel mailing list the interest to add tree-sitter support in vanilla. 
 
https://lists.gnu.org/archive/html/emacs-devel/2021-06/msg00174.html
 https://lists.gnu.org/archive/html/emacs-devel/2021-06/threads.html

This module is a very good starting point for that and it was mentioned that a very good first step is that this packages become part of the official Elpa repo.  

It would be very nice if the developers of the `emacs-tree-sitter` package join to the developer team and help with the integration too  cause you already have the experience. The integration with vanilla can improve the user experience, simplify the installation "out of the box" experience while on the other hand we can provide a better support and functionalities to make it more efficient.

WDYT?

**Comment by shackra** [comment]
@ubolonton you were ping'd here https://lists.gnu.org/archive/html/emacs-devel/2021-06/msg00177.html

**Comment by shackra** [comment]
Let's keep the discussion on https://github.com/ubolonton/emacs-tree-sitter/discussions/127
