### ISSUE TITLE
installation guide for package management other than package.el

### ISSUE THREAD

**Issue by junyi-hou** [ubolonton/emacs-tree-sitter#40]
First of all, thanks for the great work!

I'm using `straight.el` as alternative to `package.el` to manage my package. I had a hard time compile and install `emacs-tree-sitter`. I was wondering if you can provide a manual install guide.

**Comment by ubolonton** [comment]
I just released a new version that can be installed by `straight.el` without compilation. The doc is [here](https://ubolonton.github.io/emacs-tree-sitter/installation/#installing-with-straight-dot-el).

**Comment by rirze** [comment]
Could you also add the hook to the docs:

```emacs lisp
:hook (tree-sitter-after-on-hook . tree-sitter-hl-mode)
```

**Comment by junyi-hou** [comment]
Thanks! With the new documentation, I can indeed build without any problem.
