### ISSUE TITLE
unexpected highlighting for python

### ISSUE THREAD

**Issue by junyi-hou** [ubolonton/emacs-tree-sitter#42]
`tree-sitter-hl-mode` cannot correctly hightlight class names starting with underscore.

minimal example:
```
class Foo:
    pass


class _Foo:
    pass
```

behavior:
class `Foo` has `tree-sitter-hl-face:constructor` face, but class `_Foo` has `default` face.

solution:
replace
```
((identifier) @constructor
 (#match? @constructor "^[A-Z]"))
```
in `./langs/queries/python/hightlight.scm` with
```
((identifier) @constructor
 (#match? @constructor "^[A-Z_]"))
```

caveat:
I am not sure whether the current highlighting scheme is intentional (i.e., do not put `tree-sitter-hl-face:constructor` to private classes). If so, you can close the issue.

thanks!

**Comment by rirze** [comment]
This should probably be an issue for [upstream](https://github.com/tree-sitter/tree-sitter-python).

I believe that this repository's highlight.scm files inherit from tree-sitter's official language repositories. For example, Python's grammar repo has the same [constructor definition](https://github.com/tree-sitter/tree-sitter-python/blob/master/queries/highlights.scm#L3). 

Either way, it should be updated if the maintainers of the tree-sitter python repository confirm that this is a bug, and not intended.

**Comment by junyi-hou** [comment]
Got it, thanks for the reply! I'll close this one now.

**Comment by ubolonton** [comment]
> This should probably be an issue for [upstream](https://github.com/tree-sitter/tree-sitter-python).
> 
> I believe that this repository's highlight.scm files inherit from tree-sitter's official language repositories. For example, Python's grammar repo has the same [constructor definition](https://github.com/tree-sitter/tree-sitter-python/blob/master/queries/highlights.scm#L3).

Most of the queries in official language repositories are pretty bare-bone, and may not fit well with existing Emacs's conventions. It's my intention for `tree-sitter-langs` to maintain its own version of the highlighting queries. (Later on, that will be job of major modes that use tree-sitter).

In this specific case, we probably only want to special-case class definitions. I'm not sure yet.

**Comment by rirze** [comment]
> Most of the queries in official language repositories are pretty bare-bone, and may not fit well with existing Emacs's conventions.

I believe that OP's observation about underscore being used in Python class names falls within the Python naming specification. If that's the case, then it should definitely be reported upstream as this is not specific to Emacs' version of tree-sitter.

> It's my intention for tree-sitter-langs to maintain its own version of the highlighting queries.

Perfectly valid. It's great you are willing to maintain a more relevant set of grammar and query rules.

**Comment by isolet** [comment]
Is this wrong highlight an issue of `emacs-tree-sitter` or `tree-sitter`?
<img width="391" alt="Screen Shot 2020-06-28 at 11 38 34 AM" src="https://user-images.githubusercontent.com/5475262/85937219-15004a80-b934-11ea-8bd2-79ab67891014.png">

**Comment by ubolonton** [comment]
> Is this wrong highlight an issue of `emacs-tree-sitter` or `tree-sitter`?
>

This could be either. Can you provide these details for debugging?
- The file with the issue.
- Major and minor modes used in the buffer.
- Steps to trigger the behavior. For example, any navigation/editing after opening the file.
- Versions of `tree-sitter` and `tree-sitter-langs`, or git revisions, if installed by `straight.el`.
