### ISSUE TITLE
rainbow-delimiters stops working when tree-sitter-hl-mode is enabled

### ISSUE THREAD

**Issue by CSRaghunandan** [ubolonton/emacs-tree-sitter#44]
Steps to reproduce are quite simple:
1. open any file (whose major mode is supported for tree-sitter)
2. Enable  `tree-sitter-mode` and `tree-sitter-hl-mode`
3. Run `rainbow-delimiters-mode`

You can see that none of the brackets will be highlighted.

**Comment by ubolonton** [comment]
This is a known issue. Let's track it in #45.
