### ISSUE TITLE
Install grammar binaries relative to user-emacs-directory, instead of using locate-library

### ISSUE THREAD

**Issue by jsalzbergedu** [ubolonton/emacs-tree-sitter#48]
Many emacs packages, e.g. lsp-mode, install binaries relative to ~/.emacs.d and allow the binary location to be determined through a variable.

In contrast, this package installs its non-elisp data relative to the _compiled library_ (via load-library). This breaks when using gccemacs, because gccemacs compiles files into their own directory.

If you used the convention and installed into ~/.emacs.d/ , or at least allowed the user to control where the data was installed, it would fix this problem.

Thank you!

**Comment by ubolonton** [comment]
> In contrast, this package installs its non-elisp data relative to the _compiled library_ (via load-library). This breaks when using gccemacs, because gccemacs compiles files into their own directory.
>

Can you provide details on how it breaks?

> If you used the convention and installed into ~/.emacs.d/ , or at least allowed the user to control where the data was installed, it would fix this problem.
>

This is a reasonable solution for grammar binaries installed by `tree-sitter-langs.el`, as they are handled by the library itself. I'll make it customizable.

The dynamic module's binary installed by `tree-sitter.el` should be on `load-path`, as it is handled by the library loading mechanism. The directory that contains `tree-sitter.el[cn]` is currently the most sensible location. Depending on how it currently breaks on gccemacs, it may be an issue with gccemacs itself.

**Comment by jsalzbergedu** [comment]
> Can you provide details on how it breaks?

Sure!

When I native compile tree sitter, then run "tree-sitter-hl-mode" in, for instance, java, I get the error: tree-sitter-load: cannot find shared library for language: java.

Going into tree sitter I can see that it is /home/jacob/.emacs.d/straight/build/tree-sitter-langs/eln-x86_64-pc-linux-gnu-3fa98b4db038dd53/bin/

which obviously doesn't contain anything because the "eln" folder is a subfolder of the treesitter build directory, because `native-compile-async` creates a subfolder.

Thank you :)

**Comment by ubolonton** [comment]
> Going into tree sitter I can see that it is /home/jacob/.emacs.d/straight/build/tree-sitter-langs/eln-x86_64-pc-linux-gnu-3fa98b4db038dd53/bin/

Is this directory listed in `tree-sitter-load-path`? Does it contain the `.so` language files?

If you execute `M-x tree-sitter-langs-install-grammars`, where does it download the file to?

Does it work if you change the definition of `tree-sitter-langs--dir` to this?
```emacs-lisp
(defconst tree-sitter-langs--dir
  (file-name-directory (locate-library "tree-sitter-langs.el")))
```

**Comment by ubolonton** [comment]
#63 introduced the custom option `tree-sitter-langs-grammar-dir`.

Please reopen if you still encounter this issue.
