### ISSUE TITLE
Mention how to install tree-sitter-cli in README

### ISSUE THREAD

**Issue by casouri** [ubolonton/emacs-tree-sitter#5]
When I run `./bin/ensure-lang python`, it returns an error 

```
Running 'tree-sitter test' for python
./bin/ensure-lang: line 35: tree-sitter: command not found
```

And I went out to search how to install tree-sitter's cli. 

It would be nice if you mention that tree-sitter-cli is required and how to install it.

**Comment by ubolonton** [comment]
I updated README in https://github.com/ubolonton/emacs-tree-sitter/commit/21100b9e90ebf1ca585cbf334c14d6b51999ffd1
