### ISSUE TITLE
Modifying tree-sitter-langs-repos doesn't download and build new additions

### ISSUE THREAD

**Issue by dylanjm** [ubolonton/emacs-tree-sitter#54]
Perhaps I'm not groking the README right, but after modifying `tree-sitter-langs-repos` and running `make ensure/rust`, I just get the shared libraries that are located in the original bundle. Do I have to add this grammar to your bintray repo?

Steps to reproduce

1. Clone `emacs-tree-sitter`
2. Append `(hit "bdeac01")` to the end of `tree-sitter-langs-repos`
3. Run `make ensure/rust`.
4. Check `./langs/bin` for `hit.dylib`

**Comment by ubolonton** [comment]
Yeah, the README is confusing here.

>     2. Append `(hit "bdeac01")` to the end of `tree-sitter-langs-repos`

You need to specify the git repository as well, since `tree-sitter-hit` is not under the `tree-sitter` org. Like this:

```emacs-lisp
(hit        "bdeac01" nil "https://github.com/dschwen/tree-sitter-hit")
``` 

>     3. Run `make ensure/rust`.

The README is confusing here. It means `make ensure/<lang>`. In this case:

```bash
make ensure/hit
```

**Comment by dylanjm** [comment]
Ahh okay perfect. I got it working. Thank you.
