### ISSUE TITLE
Have you thought about doing a presentation in emacsconf2020?

### ISSUE THREAD

**Issue by kidd** [ubolonton/emacs-tree-sitter#57]
It'd be super cool to see this project shown there!
https://emacsconf.org/2020/cfp/

Cheers!

**Comment by ubolonton** [comment]
I'm still thinking about it. The schedule is a bit late in the evening for my timezone.

**Comment by kidd** [comment]
mm... IIRC some talks last year were prerecorded. At least the lightning talks were for sure.

Maybe this would be an affordable middleground? and if in the end you can be there at that time, you just sit and answer chat questions :).

Anyway, thanks for considering it! I think there's quite a bit of interest in the community wrt the state of emacs tree sitter and where to help/test.

**Comment by aspiers** [comment]
[**@kidd**](https://github.com/kidd) commented on [September 21, 2020 9:07 AM](https://github.com/ubolonton/emacs-tree-sitter/issues/57#issuecomment-695966309 "2020-09-21T08:07:51Z - Replied by Github Reply Comments"):
> I think there's quite a bit of interest in the community wrt the state of emacs tree sitter and where to help/test.

I second this!  I think this project is extremely significant within the emacs ecosystem :sunglasses:

**Comment by ubolonton** [comment]
I've submitted a talk proposal. I'm waiting for the response.

**Comment by kidd** [comment]
Nice!!! 
I'm sure it'll drive adoption and awareness to the project.


thanks!

**Comment by ubolonton** [comment]
The proposal has been accepted.
