### ISSUE TITLE
tree-sitter-hl-mode slows python-mode a little

### ISSUE THREAD

**Issue by KaratasFurkan** [ubolonton/emacs-tree-sitter#59]
Hi, thanks for this great package first of all.

In python-mode, when there are lots of thing to highlight (and maybe with long files like above 200), emacs is slower with tree-sitter-hl-mode. If I disable it, it speeds up. I can notice it when I hold C-n or C-p. Is it normal? I think tree-sitter supposed to be faster than font-lock.

**Comment by shackra** [comment]
> Is it normal?

it is not

> and maybe with long files like above 200

I work with an extensive amount of Go code per file and also Typescript files too to go above the 200 lines mark, and Emacs does not slow down for me.

try to reproduce this issue again and run `M-x profiler-start`, after some minutes then run `M-x profiler-report` and paste the results here.

**Comment by shackra** [comment]
@KaratasFurkan you can also use [Elisp bug hunter](https://github.com/Malabarba/elisp-bug-hunter/), this can tell you if something on your configuration along with tree-sitter is causing the slowness.

**Comment by KaratasFurkan** [comment]
@shackra i will try and update issue, thank you.

**Comment by KaratasFurkan** [comment]
![Screenshot_20201005_123035](https://user-images.githubusercontent.com/29731420/95113499-38187280-074b-11eb-839f-01a254b796ae.png)

It seems beacon-mode is the most source consuming part of my config, but removing it does not solve the lag. The smoothness difference between font-lock and tree-sitter is very little btw.

I could not test enough and I also switched to the gccemacs, lets give me a week to test more, I will code python for a while, I may update this issue. I am closing this now.

**Comment by tshu-w** [comment]
I'm facing the same issue, with the profiles below. But maybe it's the Emacs issue as redisplay_internal cost most?
<img width="2008" alt="Screen Shot 2021-06-21 at 18 23 04" src="https://user-images.githubusercontent.com/13161779/122747824-16055700-d2be-11eb-9ee5-eb532e30e605.png">
