### ISSUE TITLE
How to make spell-fu work with tree-sitter-hl?

### ISSUE THREAD

**Issue by loafofpiecrust** [ubolonton/emacs-tree-sitter#64]
If I enable `tree-sitter-hl-mode` in a buffer, it gets highlighted correctly and my `TODO` and `NOTE` items still get highlighted (by the `hl-todo` minor mode) but the misspelled words in the buffer lose their red underline from `spell-fu-mode`. Related to #45?

**Comment by ubolonton** [comment]
This is probably unrelated to #45, as `spell-fu-mode` seems to use overlays.

**Comment by ubolonton** [comment]
`spell-fu` relies on `spell-fu-faces-include`, which defaults to `'(font-lock-comment-face font-lock-doc-face font-lock-string-face). It probably needs a more generic mechanism to specify *regions to spell-check*. For now, this should be enough:

```emacs-lisp
(setq-default spell-fu-faces-include
              '(tree-sitter-hl-face:comment
                tree-sitter-hl-face:doc
                tree-sitter-hl-face:string
                font-lock-comment-face
                font-lock-doc-face
                font-lock-string-face))
```

**Comment by loafofpiecrust** [comment]
That seems to do the trick, thanks!
