### ISSUE TITLE
Wrong highlighting of field declarations in c/c++

### ISSUE THREAD

**Issue by xzz53** [ubolonton/emacs-tree-sitter#67]
Hi!
In field declarations within structs/classes only the first field in comma separated lists of fields having common type gets assigned correct face (`tree-sitter-hl-face:property.definition`). The rest fields are assigned only `(tree-sitter-hl-face:property)`. Also see screenshot below. I use https://github.com/ubolonton/emacs-tree-sitter/commit/f5065c86b067577d162850af21598921128bd33b with Emacs 27.1.

![image](https://user-images.githubusercontent.com/31386028/97818311-cfbda200-1cb2-11eb-80b2-dd3072a2546d.png)

**Comment by ubolonton** [comment]
This seems to be an upstream issue: https://github.com/tree-sitter/tree-sitter/issues/790.

**Comment by xzz53** [comment]
Thanks for forwarding this to the right place!

By the way, at least https://github.com/ubolonton/emacs-tree-sitter/blob/f5065c86b067577d162850af21598921128bd33b/langs/queries/python/highlights.scm#L27 seems to be affected by the same kind of issue.

**Comment by xzz53** [comment]
I confirm that after updating to the most recent release of tree-sitter rust bindings the issue is gone.
```diff
diff --git a/core/Cargo.toml b/core/Cargo.toml
index a2a3c5a..10f41f3 100644
--- a/core/Cargo.toml
+++ b/core/Cargo.toml
@@ -13,5 +13,5 @@ crate-type = ["cdylib"]
 [dependencies]
 emacs = "0.14.1"
 libloading = "0.6.2"
-tree-sitter = "0.17.0"
+tree-sitter = "0.17.1"
 once_cell = "1.2.0"
```
