### ISSUE TITLE
Syntax highlighting doesn't work for java annotations with scoped_identifier

### ISSUE THREAD

**Issue by rrudakov** [ubolonton/emacs-tree-sitter#71]
**To reproduce:**
1. Create java class:
```java
@Config.Source("any value")
public class Test {
  
}
```
2. Add the following to init.el:
```emacs-lisp
(tree-sitter-hl-add-patterns 'java
    [
     ;; Scoped annotations
     (annotation
      (scoped_identifier) @parameter)

     (marker_annotation
      (scoped_identifier) @parameter)
     ])
```
**Expected result:**
- Annotation highlighted using `tree-sitter-hl-face:parameter`

**Actual result:**
- `Config` part highlighted using `tree-sitter-hl-face:type` face and `.Source` part highlighted using `default` face.

**Emacs version:** 
GNU Emacs 27.1 (build 2, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw3d scroll bars) of 2020-08-11
![tree-sitter-bug](https://user-images.githubusercontent.com/6093590/98826694-518d9800-2436-11eb-971f-4f1e096bc0eb.png)

**Comment by ubolonton** [comment]
`tree-sitter-hl-face:parameter` is not a valid face. Capture names that would be highlighted are `@variable.parameter` and `@type.parameter`.
However, this specific Java construct should probably be `@function.special` (like Python) or `@function.macro` (like Rust) instead.

**Comment by rrudakov** [comment]
Sorry, my bad. It was just invalid face name.
