### ISSUE TITLE
Using tree-sitter to calculate indentation

### ISSUE THREAD

**Issue by muirdm** [ubolonton/emacs-tree-sitter#77]
Has anyone tried to implement `indent-line-function` using tree-sitter? It doesn't seem like tree-sitter provides a facility for that, but it also seems very similar to the local/scope tracking.

**Comment by sogaiu** [comment]
I'm not sure, but the following has come up here before: https://codeberg.org/FelipeLema/tree-sitter-indent.el

Perhaps it's relevant?

**Comment by muirdm** [comment]
Yes, thanks! I will play around with that.
