### ISSUE TITLE
Dynamic module requires installing VC++ runtime on Windows

### ISSUE THREAD

**Issue by morganwillcock** [ubolonton/emacs-tree-sitter#86]
In order to successfully load the supplied 'tsc-dyn.dll' file with `module-load` it seems to be a requirement to have VC++ runtime installed, but this isn't mentioned in the [installation instructions](https://ubolonton.github.io/emacs-tree-sitter/installation/). Without this being present `module-load` returns "The specified module could not be found."

In order to fix this I had to install the 'Visual C++ redistributable package for Visual Studio 2015, 2017 and 2019' package from here:

https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads

**Comment by ubolonton** [comment]
Static linking would probably be better than requiring users to install the VC++ redistributable package. 

I'll check this when I have access to my Windows machine again.
