### ISSUE TITLE
Can't get Syntax Highlighting to work for Java in Spacemacs / lsp-mode

### ISSUE THREAD

**Issue by muhmud** [ubolonton/emacs-tree-sitter#87]
I've added the packages like this:
```
dotspacemacs-additional-packages '(tree-sitter tree-sitter-langs)
```

I've added this to user config:
```
(require 'tree-sitter)
(require 'tree-sitter-langs)
```

I've added this:
```
(add-hook 'java-mode-hook #'tree-sitter-mode)
(add-hook 'java-mode-hook #'tree-sitter-hl-mode)
```

I have executed `tree-sitter-langs-install-grammars` and as far as I can tell, the languages have been installed.

When I open a Java file, I can see that `Tree-Sitter-Hl` mode is active, but none of the syntax highlighting has changed. What am I doing wrong?

**Comment by ubolonton** [comment]
Can you check the following variables, to see whether they have these expected buffer-local values (in the Java buffer)?
- `font-lock-mode`: t
- `font-lock-defaults`: nil
- `font-lock-set-defaults`: t
- `font-lock-fontify-region-function`: should have `tree-sitter-hl--highlight-region` inside its definition.
- `jit-lock-mode`: t
- `jit-lock-functions`: `(font-lock-fontify-region)`
- `tree-sitter-hl--query`: non-nil
- `tree-sitter-hl--query-cursor`: non-nil
- `tree-sitter-language`: non-nil

You can also try checking what faces are being used to highlight some code, by putting the cursor on a highlighted piece of text, and evaluate one of these:

```emacs-lisp
(get-text-property (point) 'face)

(what-cursor-position 4)
```

**Comment by muhmud** [comment]
Thanks for helping me work through this, most of those variables do not have the expected values:

- `font-lock-set-defaults`: nil
- `font-lock-fontify-region-function`: font-lock-default-fontify-region
- `jit-lock-mode`: nil
- `jit-lock-functions`: nil
- `tree-sitter-hl--query`: nil
- `tree-sitter-hl--query-cursor`: nil
- `tree-sitter-language`: nil

So, it seems like tree-sitter didn't fully load. If I run `tree-sitter-debug-mode`, I does output an AST, so I think it's kind of working. No errors in messages.

**Comment by muhmud** [comment]
OK, I have taken a completely vanilla install of the Spacemacs develop branch:

```
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
```

Then did just the steps described above, with nothing else installed, and those variables still do not have the right values. They have the same values I posted before.

Not sure what further info I can provide?

**Comment by muhmud** [comment]
You're completely correct, it came down to the faces!

The global value of `tree-sitter-language` was nil but there is a buffer local value. I reason this stumped me is that all the colours look exactly the same as they did before, which made me think it wasn't working.

Thanks very much! I know just need to figure out how to add some custom rules/faces.
