### ISSUE TITLE
highlighting misbehaves in Typescript 

### ISSUE THREAD

**Issue by shackra** [ubolonton/emacs-tree-sitter#97]
I believe this is due to back ticks (`) use on code. Here are some screenshots:

![Captura de Pantalla 2021-01-14 a la(s) 09 49 56](https://user-images.githubusercontent.com/1055216/104614808-331e6580-564e-11eb-9f65-4f0fc5b152d0.png)

`tree-sitter-hl-mode` turned off:

![Captura de Pantalla 2021-01-14 a la(s) 09 50 08](https://user-images.githubusercontent.com/1055216/104614860-3fa2be00-564e-11eb-86a1-bd247f0c6201.png)

**Comment by ubolonton** [comment]
Please provide reproducible TypeScript code for this.

**Comment by ubolonton** [comment]
Please reopen this in [tree-sitter-langs](https://github.com/ubolonton/tree-sitter-langs) if it can be reproduced.
